# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525f1948a502016c44bdece517c4fc0cf9d14f33db4a116bd61b903610fc60f3d76abb79fc8030159ad80425ea8979985a42cf61a7196532cbdc6e6617834e5c

test:
  secret_key_base: e4bcebd38f03160b0d13f0c03db3726cfa7acf2bdca2a04c51b817a26aed647cc05768457d3108010fa54dcaabbc804974fcc11a9603b08fef9dab2469ed2d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
